version: '3.9'

services: 
  #MONGO SERVICE
  task_manager_mongo_db:
    container_name: mongodb_task_manager
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  task_manager_redis:
    container_name: redis_task_manager
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis/db
    
  
  #API NODE
  task_manager_api:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      # local->container
      - 8000:8000
    environment:
      APP_PORT: 8000
      MONGODB_URI: mongodb://task_manager_mongo_db:27017
      DB_NAME: task_manager_db
    depends_on:
      - task_manager_mongo_db

volumes:
  mongo_data: {}
  redis_data: {}

